# data_grammar.py
# Database 100 Soal Grammar TOEFL Standard

db_grammar = [
    {"soal": "The coffee _______ much better this morning.", "pilihan": ["A. is", "B. are", "C. has", "D. have"], "jawaban": "A"},
    {"soal": "Neither the students nor the instructor _______ happy with the new schedule.", "pilihan": ["A. are", "B. were", "C. is", "D. have been"], "jawaban": "C"},
    {"soal": "The report _______ by the committee before the deadline yesterday.", "pilihan": ["A. finishes", "B. was finished", "C. has finished", "D. finishing"], "jawaban": "B"},
    {"soal": "By the time the manager arrived, the presentation _______.", "pilihan": ["A. had already started", "B. already starts", "C. has already started", "D. starting"], "jawaban": "A"},
    {"soal": "The results of the study _______ expected to be published.", "pilihan": ["A. is", "B. are", "C. has", "D. being"], "jawaban": "B"},
    {"soal": "The new software is designed to _______ the workflow.", "pilihan": ["A. facilitation", "B. facilitative", "C. facilitate", "D. facilitator"], "jawaban": "C"},
    {"soal": "Despite _______ highly educated, he struggled to find a job.", "pilihan": ["A. he was", "B. of being", "C. being", "D. is"], "jawaban": "C"},
    {"soal": "The car, _______ costs $50,000, is very fast.", "pilihan": ["A. that", "B. which", "C. who", "D. what"], "jawaban": "B"},
    {"soal": "It is essential that every student _______ the rules.", "pilihan": ["A. obey", "B. obeys", "C. obeyed", "D. obeying"], "jawaban": "A"},
    {"soal": "The data _______ collected by the research team last year.", "pilihan": ["A. was", "B. were", "C. has been", "D. being"], "jawaban": "A"},
    {"soal": "Not only _______ the project on time, but they also stayed under budget.", "pilihan": ["A. they finished", "B. did they finish", "C. they finishing", "D. they did finish"], "jawaban": "B"},
    {"soal": "The company, _______ by a group of engineers, specializes in AI.", "pilihan": ["A. founded", "B. founding", "C. was founded", "D. was founding"], "jawaban": "A"},
    {"soal": "The software is _______ complex that it requires a manual.", "pilihan": ["A. such", "B. very", "C. so", "D. too"], "jawaban": "C"},
    {"soal": "Hardly _______ the office when the phone rang.", "pilihan": ["A. I had left", "B. had I left", "C. I left", "D. was I leaving"], "jawaban": "B"},
    {"soal": "The new laptop is _______ than the previous model.", "pilihan": ["A. more faster", "B. fastest", "C. much faster", "D. as faster"], "jawaban": "C"},
    {"soal": "She is looking forward _______ her thesis next month.", "pilihan": ["A. to finish", "B. finishing", "C. to finishing", "D. for finishing"], "jawaban": "C"},
    {"soal": "The professor suggested that the student _______ more research.", "pilihan": ["A. do", "B. does", "C. did", "D. doing"], "jawaban": "A"},
    {"soal": "If I _______ you, I would take the job offer.", "pilihan": ["A. am", "B. was", "C. were", "D. be"], "jawaban": "C"},
    {"soal": "Rarely _______ such a beautiful sunset.", "pilihan": ["A. I see", "B. do I see", "C. I have seen", "D. am I seeing"], "jawaban": "B"},
    {"soal": "The committee _______ the proposal for three hours now.", "pilihan": ["A. discusses", "B. is discussing", "C. has been discussing", "D. discussed"], "jawaban": "C"},
    {"soal": "The more you practice, _______ you will become.", "pilihan": ["A. the better", "B. the best", "C. better", "D. best"], "jawaban": "A"},
    {"soal": "I would rather _______ at home tonight.", "pilihan": ["A. to stay", "B. stay", "C. staying", "D. stayed"], "jawaban": "B"},
    {"soal": "No sooner _______ the game started than it began to rain.", "pilihan": ["A. had", "B. did", "C. has", "D. was"], "jawaban": "A"},
    {"soal": "The bridge _______ since 1990 is being repaired.", "pilihan": ["A. built", "B. building", "C. was built", "D. which built"], "jawaban": "A"},
    {"soal": "Unless it _______, we will go for a walk.", "pilihan": ["A. rains", "B. will rain", "C. raining", "D. rained"], "jawaban": "A"},
    {"soal": "He avoided _______ her the truth to prevent a fight.", "pilihan": ["A. to tell", "B. tell", "C. telling", "D. told"], "jawaban": "C"},
    {"soal": "The news _______ not as bad as we expected.", "pilihan": ["A. are", "B. were", "C. is", "D. being"], "jawaban": "C"},
    {"soal": "She acted as if she _______ the boss.", "pilihan": ["A. is", "B. was", "C. were", "D. be"], "jawaban": "C"},
    {"soal": "The books _______ on the table belong to the library.", "pilihan": ["A. laying", "B. are laying", "C. lying", "D. lain"], "jawaban": "C"},
    {"soal": "Scarcely _______ the door when the dog ran out.", "pilihan": ["A. he opened", "B. did he open", "C. had he opened", "D. opened he"], "jawaban": "C"},
    {"soal": "He _______ his car serviced yesterday.", "pilihan": ["A. has", "B. had", "C. having", "D. have"], "jawaban": "B"},
    {"soal": "I am used to _______ up early in the morning.", "pilihan": ["A. wake", "B. woke", "C. waking", "D. waken"], "jawaban": "C"},
    {"soal": "The manager made the staff _______ late to finish the report.", "pilihan": ["A. work", "B. to work", "C. working", "D. worked"], "jawaban": "A"},
    {"soal": "She has her brother _______ her homework every day.", "pilihan": ["A. do", "B. to do", "C. doing", "D. done"], "jawaban": "A"},
    {"soal": "I suggest _______ a doctor if the pain continues.", "pilihan": ["A. to see", "B. seeing", "C. see", "D. saw"], "jawaban": "B"},
    {"soal": "He is the only one of the students who _______ passed the exam.", "pilihan": ["A. have", "B. has", "C. having", "D. had"], "jawaban": "B"},
    {"soal": "A number of students _______ waiting outside.", "pilihan": ["A. is", "B. are", "C. has", "D. have"], "jawaban": "B"},
    {"soal": "The number of students in the class _______ fifty.", "pilihan": ["A. is", "B. are", "C. has", "D. have"], "jawaban": "A"},
    {"soal": "It's time you _______ studying for the test.", "pilihan": ["A. start", "B. started", "C. starting", "D. to start"], "jawaban": "B"},
    {"soal": "I wish I _______ more money.", "pilihan": ["A. have", "B. has", "C. having", "D. had"], "jawaban": "D"},
    {"soal": "The teacher, along with her students, _______ going to the museum.", "pilihan": ["A. is", "B. are", "C. am", "D. were"], "jawaban": "A"},
    {"soal": "Neither of the boys _______ his homework.", "pilihan": ["A. have done", "B. has done", "C. do", "D. doing"], "jawaban": "B"},
    {"soal": "Each of the girls _______ a unique talent.", "pilihan": ["A. have", "B. has", "C. having", "D. had"], "jawaban": "B"},
    {"soal": "Physics _______ my favorite subject in high school.", "pilihan": ["A. were", "B. are", "C. is", "D. am"], "jawaban": "C"},
    {"soal": "Two hundred dollars _______ a lot of money to lose.", "pilihan": ["A. are", "B. were", "C. is", "D. am"], "jawaban": "C"},
    {"soal": "Either the mayor or his deputies _______ attending the meeting.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "The jury _______ divided in their opinions.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "The scissors _______ in the top drawer.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "Most of the pie _______ been eaten.", "pilihan": ["A. has", "B. have", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "Most of the students _______ finished their assignments.", "pilihan": ["A. has", "B. have", "C. is", "D. are"], "jawaban": "B"},
    {"soal": "Here _______ the news you have been waiting for.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "There _______ several reasons for this decision.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "He is one of those people who _______ always complaining.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "Nobody but the guards _______ allowed in the building.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Everything _______ ready for the party.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Some of the water _______ spilled on the floor.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "Some of the apples _______ rotten.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "B"},
    {"soal": "Ten miles _______ a long way to walk.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The committee _______ reached a unanimous decision.", "pilihan": ["A. has", "B. have", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "My family _______ planning a vacation.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The flock of birds _______ flying south.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "A pair of shoes _______ missing from the closet.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The police _______ investigating the crime.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "The cattle _______ grazing in the field.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "The rich _______ not always happy.", "pilihan": ["A. is", "B. are", "C. was", "D. has"], "jawaban": "B"},
    {"soal": "The blind _______ assistance to cross the street.", "pilihan": ["A. need", "B. needs", "C. needing", "D. needed"], "jawaban": "A"},
    {"soal": "Measles _______ a highly contagious disease.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Gymnastics _______ my sister's favorite sport.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The United States _______ a large country.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The Netherlands _______ located in Europe.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Gulliver's Travels _______ written by Jonathan Swift.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "C"},
    {"soal": "Star Wars _______ a popular movie franchise.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Mathematics _______ essential for engineering.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Economics _______ a difficult subject for many.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Statistics _______ used in many fields of research.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "A group of tourists _______ waiting for the guide.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The team _______ playing well today.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The staff _______ working hard on the project.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The public _______ informed about the incident.", "pilihan": ["A. was", "B. were", "C. is", "D. has"], "jawaban": "A"},
    {"soal": "The youth _______ the future of the nation.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "B"},
    {"soal": "Many a student _______ struggled with this concept.", "pilihan": ["A. has", "B. have", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "More than one person _______ involved in the accident.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "Half of the cake _______ left.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "Half of the apples _______ gone.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "B"},
    {"soal": "All of the information _______ correct.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "All of the students _______ present.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "B"},
    {"soal": "None of the money _______ recovered.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "None of the keys _______ the lock.", "pilihan": ["A. fit", "B. fits", "C. fitting", "D. fitted"], "jawaban": "B"},
    {"soal": "A lot of time _______ wasted on this project.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "A lot of people _______ attending the concert.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "B"},
    {"soal": "The majority of the population _______ voted.", "pilihan": ["A. has", "B. have", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "The majority of the voters _______ in favor.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "B"},
    {"soal": "Plenty of evidence _______ presented.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "Plenty of chairs _______ available.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "B"},
    {"soal": "A percentage of the profits _______ donated to charity.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "A large percentage of the students _______ passed.", "pilihan": ["A. has", "B. have", "C. is", "D. are"], "jawaban": "B"},
    {"soal": "The rest of the story _______ unknown.", "pilihan": ["A. is", "B. are", "C. was", "D. were"], "jawaban": "A"},
    {"soal": "The rest of the books _______ sold.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "B"},
    {"soal": "Some of the cake _______ eaten.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "A"},
    {"soal": "Some of the boys _______ late.", "pilihan": ["A. was", "B. were", "C. is", "D. are"], "jawaban": "B"}
]